import unittest

from y2024.d08.resonant_collinearity import ResonantCollinearity


# noinspection SpellCheckingInspection
class ResonantCollinearityTestCase(unittest.TestCase):
    def test_antinodes_count_simple(self):
        simple_map = [
            "..........", #  ..........
            "..........", #  ...#......
            "..........", #  ..........
            "....a.....", #  ....a.....
            "..........", #  ..........
            ".....a....", #  .....a....
            "..........", #  ..........
            "..........", #  ......#...
            "..........", #  ..........
            ".........."  #  ..........
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(2, resonant_collinearity.get_antinodes_count())

    def test_antinodes_count_simple_22(self):
        simple_map = [
            "...",
            ".a.",
            ".a.",
            "..."
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(2, resonant_collinearity.get_antinodes_count())



    def test_antinodes_count_simple2(self):
        simple_map = [
            "..........", # ..........
            "..........", # ...#......
            "..........", # #.........
            "....a.....", # ....a.....
            "........a.", # ........a.
            ".....a....", # .....a....
            "..........", # ..#.......
            "..........", # ......#...
            "..........", # ..........
            ".........."  # ..........
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(4, resonant_collinearity.get_antinodes_count())

    def test_antinodes_count_simple3(self):
        simple_map = [
            "..........", # ..........
            "..........", # ...#......
            "..........", # #.........
            "....a.....", # ....a.....
            "........a.", # ........a.
            ".....a....", # .....a....
            "..........", # ..#.......
            "......A...", # ......A...
            "..........", # ..........
            ".........."  # ..........
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(4, resonant_collinearity.get_antinodes_count())

    def test_antinodes_count(self):
        simple_map = [
            "............", # ......#....#
            "........0...", # ...#....0...
            ".....0......", # ....#0....#.
            ".......0....", # ..#....0....
            "....0.......", # ....0....#..
            "......A.....", # .#....A.....
            "............", # ...#........
            "............", # #......#....
            "........A...", # ........A...
            ".........A..", # .........A..
            "............", # ..........#.
            "............", # ..........#.
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(14, resonant_collinearity.get_antinodes_count())

    def test_get_antinodes_count_distance_simple(self):
        simple_map = [
            "T.........",
            "...T......",
            ".T........",
            "..........",
            "..........",
            "..........",
            "..........",
            "..........",
            "..........",
            ".........."
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(9, resonant_collinearity.get_antinodes_count_distance_multiplier())

    def test_get_antinodes_count_distance(self):
        simple_map = [
            "............", # ##....#....#
            "........0...", # .#.#....0...
            ".....0......", # ..#.#0....#.
            ".......0....", # ..##...0....
            "....0.......", # ....0....#..
            "......A.....", # .#...#A....#
            "............", # ...#..#.....
            "............", # #....#.#....
            "........A...", # ..#.....A...
            ".........A..", # ....#....A..
            "............", # .#........#.
            "............", # ...#......##
        ]
        resonant_collinearity = ResonantCollinearity(simple_map)
        self.assertEqual(34, resonant_collinearity.get_antinodes_count_distance_multiplier())

if __name__ == '__main__':
    unittest.main()
